name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest stable rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install protoc
        uses: arduino/setup-protoc@v3

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose --all-features
