name: Rust

on:
  push:
    branches: [ "wip" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest stable rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install required cargo
        run: cargo install clippy-sarif sarif-fmt

      - name: Install protoc
        uses: arduino/setup-protoc@v3

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose --all-features

      - name: Run rust-clippy
        run:
          cargo clippy
          --all-features
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true
